name: Build and Test Impellor-V3
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG_VERBOSE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install CMake
        uses: actions/setup-cmake@v1
        with:
          cmake-version: '3.28'
      - name: Check disk space
        run: dir
        shell: powershell
      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          git fetch --unshallow
          .\bootstrap-vcpkg.bat
        shell: powershell
      - name: Install dependencies
        run: |
          for ($i = 0; $i -lt 3; $i++) {
            Write-Output "Attempt $($i+1) to install vcpkg dependencies"
            .\vcpkg\vcpkg.exe install pcl[vtk,visualization,surface]:x64-windows-static opencascade:x64-windows-static nlohmann-json:x64-windows-static
            if ($?) { break }
            Start-Sleep -Seconds 10
          }
          if (-not $?) { Write-Error "Failed to install vcpkg dependencies after 3 attempts"; exit 1 }
        shell: powershell
      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$pwd/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_BUILD_TYPE=Release
        shell: powershell
      - name: Build with CMake
        run: |
          cmake --build build --config Release --verbose
        shell: powershell
      - name: Create output directory
        run: |
          New-Item -ItemType Directory -Force -Path output
        shell: powershell
      - name: Validate test.obj and config.json
        run: |
          if (-not (Test-Path test.obj)) { Write-Error "test.obj not found in repository root"; exit 1 }
          if (-not (Test-Path config.json)) { Write-Error "config.json not found in repository root"; exit 1 }
        shell: powershell
      - name: Run the compiled binary
        run: |
          $env:Path += ";$pwd\build\Release"
          .\build\Release\fit.exe $pwd\config.json
        shell: powershell
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: impellor-v3-artifacts
          path: |
            build/Release/fit.exe
            output/fit.pcd
