yaml
name: Build and Test Impellor-V3
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG_VERBOSE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          git fetch --unshallow
          .\bootstrap-vcpkg.bat
      - name: Install dependencies
        run: .\vcpkg\vcpkg.exe install pcl[vtk,visualization,surface]:x64-windows-static opencascade:x64-windows-static nlohmann-json:x64-windows-static
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_BUILD_TYPE=Release
      - name: Build with CMake
        run: cmake --build build --config Release --verbose
      - name: Create output directory
        run: mkdir output
      - name: Run the compiled binary
        run: .\build\Release\fit.exe config.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: impellor-v3-artifacts
          path: |
            build/Release/fit.exe
            output/fit.pcd
```
